version: '3.1'
services:
  db:
    image: "postgres:11.2-alpine"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "krecruiter"
    ports:
      - "6000:5432"
  adminer:
    image: "adminer:4.7.5-standalone"
    environment:
      ADMINER_DESIGN: "pepa-linha"
      ADMINER_DEFAULT_SERVER: "db"
    ports:
      - "900:8080"
    depends_on:
      - "db"
  address-validation-service:
    image: "phauer/address-validation-service-stub:latest"
    ports:
      - "5000:5000"